export const geoIApps = {
  zh_MO: {
    id: "zh_MO",
    sourceLocale: "src_zh_MO",
    language: "Chinese",
    territory: "Macao",
    tier: "C",
    region: "GC",
    isoLanguageCode: "zh",
    isoCountryCode: "MO",
    stageRootPath: "/mo",
    storeRootPath: "",
    uiDisplay: "MOTC",
    textDirection: "ltr",
    isoCurrencyCode: "MOP",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "zh-Hant-HK",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/mo",
      store: "",
      goto: "",
      support: "https://support.testurl.com/zh-mo",
      locate: "https://locate.testurl.com/mo/zh",
      jobs: "/careers/mo",
      search: "",
      education: "",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  de_AT: {
    id: "de_AT",
    sourceLocale: "src_de_AT",
    language: "German",
    territory: "Austria",
    tier: "B",
    region: "EU",
    isoLanguageCode: "de",
    isoCountryCode: "AT",
    stageRootPath: "/at",
    storeRootPath: "/at",
    uiDisplay: "AT",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage (AT)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "de-DE",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/at",
      store: "/at",
      goto: "/at/shop/goto",
      support: "https://support.testurl.com/de-at",
      locate: "https://locate.testurl.com/at/de",
      jobs: "/careers/at",
      search: "/at/search",
      education: "/at-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_CA: {
    id: "en_CA",
    sourceLocale: "src_en_CA",
    language: "English",
    territory: "Canada",
    tier: "A",
    region: "CA",
    isoLanguageCode: "en",
    isoCountryCode: "CA",
    stageRootPath: "/ca",
    storeRootPath: "/ca",
    uiDisplay: "CA",
    textDirection: "ltr",
    isoCurrencyCode: "CAD",
    homePageTitle: "Homepage (Canada)",
    pageTitleSuffix: "Homepage (CA)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-CA",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/ca",
      store: "/ca",
      goto: "/ca/shop/goto",
      support: "https://support.testurl.com/en-ca",
      locate: "https://locate.testurl.com/ca/en",
      jobs: "/careers/ca",
      search: "/ca/search",
      education: "/ca_edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  ko_KR: {
    id: "ko_KR",
    sourceLocale: "src_ko_KR",
    language: "Korean",
    territory: "South Korea",
    tier: "A",
    region: "KR",
    isoLanguageCode: "ko",
    isoCountryCode: "KR",
    stageRootPath: "/kr",
    storeRootPath: "/kr",
    uiDisplay: "KR",
    textDirection: "ltr",
    isoCurrencyCode: "KRW",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage (KR)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "ko-KR",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/kr",
      store: "/kr",
      goto: "/kr/shop/goto",
      support: "https://support.testurl.com/ko-kr",
      locate: "https://locate.testurl.com/kr/ko",
      jobs: "/careers/kr",
      search: "/kr/search",
      education: "/kr-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  fr_FR: {
    id: "fr_FR",
    sourceLocale: "src_fr_FR",
    language: "French",
    territory: "France",
    tier: "A",
    region: "EU",
    isoLanguageCode: "fr",
    isoCountryCode: "FR",
    stageRootPath: "/fr",
    storeRootPath: "/fr",
    uiDisplay: "FR",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (France)",
    pageTitleSuffix: "Homepage (FR)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "fr-FR",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/fr",
      store: "/fr",
      goto: "/fr/shop/goto",
      support: "https://support.testurl.com/fr-fr",
      locate: "https://locate.testurl.com/fr/fr",
      jobs: "/careers/fr",
      search: "/fr/search",
      education: "/fr-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  fr_CH: {
    id: "fr_CH",
    sourceLocale: "src_fr_CH",
    language: "French",
    territory: "Switzerland",
    tier: "B",
    region: "EU",
    isoLanguageCode: "fr",
    isoCountryCode: "CH",
    stageRootPath: "/chfr",
    storeRootPath: "/ch-fr",
    uiDisplay: "CHFR",
    textDirection: "ltr",
    isoCurrencyCode: "CHF",
    homePageTitle: "Homepage (Suisse)",
    pageTitleSuffix: "Homepage (CH)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "fr-FR",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/chfr",
      store: "/ch-fr",
      goto: "/ch-fr/shop/goto",
      support: "https://support.testurl.com/fr-ch",
      locate: "https://locate.testurl.com/ch/fr",
      jobs: "/careers/chfr",
      search: "/ch-fr/search",
      education: "/ch-fr-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  de_CH: {
    id: "de_CH",
    sourceLocale: "src_de_CH",
    language: "German",
    territory: "Switzerland",
    tier: "B",
    region: "EU",
    isoLanguageCode: "de",
    isoCountryCode: "CH",
    stageRootPath: "/chde",
    storeRootPath: "/ch-de",
    uiDisplay: "CHDE",
    textDirection: "ltr",
    isoCurrencyCode: "CHF",
    homePageTitle: "Homepage (Schweiz)",
    pageTitleSuffix: "Homepage (CH)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "de-DE",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/chde",
      store: "/ch-de",
      goto: "/ch-de/shop/goto",
      support: "https://support.testurl.com/de-ch",
      locate: "https://locate.testurl.com/ch/de",
      jobs: "/careers/chde",
      search: "/ch-de/search",
      education: "/ch-de-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  es_MX: {
    id: "es_MX",
    sourceLocale: "src_es_MX",
    language: "Spanish",
    territory: "Mexico",
    tier: "A",
    region: "ALAC",
    isoLanguageCode: "es",
    isoCountryCode: "MX",
    stageRootPath: "/mx",
    storeRootPath: "/mx",
    uiDisplay: "MX",
    textDirection: "ltr",
    isoCurrencyCode: "MXN",
    homePageTitle: "Homepage (Mexico)",
    pageTitleSuffix: "Homepage (MX)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "es-MX",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/mx",
      store: "/mx",
      goto: "/mx/shop/goto",
      support: "https://support.testurl.com/es-mx",
      locate: "https://locate.testurl.com/mx/es",
      jobs: "/careers/mx",
      search: "/mx/search",
      education: "/mx-hed/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  fr_CA: {
    id: "fr_CA",
    sourceLocale: "src_fr_CA",
    language: "French",
    territory: "Canada",
    tier: "A",
    region: "CA",
    isoLanguageCode: "fr",
    isoCountryCode: "CA",
    stageRootPath: "/ca/fr",
    storeRootPath: "/xf",
    uiDisplay: "CAFR",
    textDirection: "ltr",
    isoCurrencyCode: "CAD",
    homePageTitle: "Homepage (Canada)",
    pageTitleSuffix: "Homepage (CA)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "fr-CA",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/ca/fr",
      store: "/xf",
      goto: "/xf/shop/goto",
      support: "https://support.testurl.com/fr-ca",
      locate: "https://locate.testurl.com/ca/fr",
      jobs: "/careers/ca/fr",
      search: "/xf/search",
      education: "/xf_edu_428531/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  zh_CN: {
    id: "zh_CN",
    sourceLocale: "src_zh_CN",
    language: "Chinese",
    territory: "China",
    tier: "A",
    region: "GC",
    isoLanguageCode: "zh",
    isoCountryCode: "CN",
    stageRootPath: "/cn",
    storeRootPath: "/",
    uiDisplay: "CN",
    textDirection: "ltr",
    isoCurrencyCode: "CNY",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "zh-Hans-CN",
      ruts: {
        storefrontId: "",
      },
    },
    urlPaths: {
      marcom: "",
      store: "",
      goto: "/cn/shop/goto",
      support: "https://support.testurl.com/zh-cn",
      locate: "https://locate.testurl.com/cn/zh",
      jobs: "https://www.apple.com/careers/cn",
      search: "/search",
      education: "/cn-edu/shop",
      previewDomain: "testurl.com.cn",
      previewNamespace: "preview",
    },
  },
  es_CL: {
    id: "es_CL",
    sourceLocale: "src_es_CL",
    language: "Spanish",
    territory: "Chile",
    tier: "A",
    region: "ALAC",
    isoLanguageCode: "es",
    isoCountryCode: "CL",
    stageRootPath: "/cl",
    storeRootPath: "/cl",
    uiDisplay: "CL",
    textDirection: "ltr",
    isoCurrencyCode: "CLP",
    homePageTitle: "Homepage (Chile)",
    pageTitleSuffix: "Homepage (CL)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "es-MX",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/cl",
      store: "/cl",
      goto: "/cl/shop/goto",
      support: "https://support.testurl.com/es-cl",
      locate: "https://locate.testurl.com/cl/es",
      jobs: "/careers/cl",
      search: "/cl/search",
      education: "/cl-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  it_IT: {
    id: "it_IT",
    sourceLocale: "src_it_IT",
    language: "Italian",
    territory: "Italy",
    tier: "A",
    region: "EU",
    isoLanguageCode: "it",
    isoCountryCode: "IT",
    stageRootPath: "/it",
    storeRootPath: "/it",
    uiDisplay: "IT",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Italia)",
    pageTitleSuffix: "Homepage (IT)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "it-IT",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/it",
      store: "/it",
      goto: "/it/shop/goto",
      support: "https://support.testurl.com/it-it",
      locate: "https://locate.testurl.com/it/it",
      jobs: "/careers/it",
      search: "/it/search",
      education: "/it-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  fi_FI: {
    id: "fi_FI",
    sourceLocale: "src_fi_FI",
    language: "Finnish",
    territory: "Finland",
    tier: "B",
    region: "EU",
    isoLanguageCode: "fi",
    isoCountryCode: "FI",
    stageRootPath: "/fi",
    storeRootPath: "/fi",
    uiDisplay: "FI",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Suomi)",
    pageTitleSuffix: "Homepage (FI)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "fi-FI",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/fi",
      store: "/fi",
      goto: "/fi/shop/goto",
      support: "https://support.testurl.com/fi-fi",
      locate: "https://locate.testurl.com/fi/fi",
      jobs: "/careers/fi",
      search: "/fi/search",
      education: "/fi-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  zh_HK: {
    id: "zh_HK",
    sourceLocale: "src_zh_HK",
    language: "Chinese",
    territory: "Hong Kong",
    tier: "B",
    region: "GC",
    isoLanguageCode: "zh",
    isoCountryCode: "HK",
    stageRootPath: "/hk",
    storeRootPath: "/hk-zh",
    uiDisplay: "HKTC",
    textDirection: "ltr",
    isoCurrencyCode: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "zh-Hant-HK",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/hk",
      store: "/hk-zh",
      goto: "/hk-zh/shop/goto",
      support: "https://support.testurl.com/zh-hk",
      locate: "https://locate.testurl.com/hk/zh",
      jobs: "/careers/hk",
      search: "/hk-zh/search",
      education: "/hk-zh-hiEd/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_GB: {
    id: "en_GB",
    sourceLocale: "src_en_GB",
    language: "English",
    territory: "United Kingdom",
    tier: "A",
    region: "EU",
    isoLanguageCode: "en",
    isoCountryCode: "GB",
    stageRootPath: "/uk",
    storeRootPath: "/uk",
    uiDisplay: "UK",
    textDirection: "ltr",
    isoCurrencyCode: "GBP",
    homePageTitle: "Homepage (United Kingdom)",
    pageTitleSuffix: "Homepage (UK)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-GB",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/uk",
      store: "/uk",
      goto: "/uk/shop/goto",
      support: "https://support.testurl.com/en-gb",
      locate: "https://locate.testurl.com/uk/en",
      jobs: "/careers/uk",
      search: "/uk/search",
      education: "/uk-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  no_NO: {
    id: "no_NO",
    sourceLocale: "src_no_NO",
    language: "Norwegian",
    territory: "Norway",
    tier: "B",
    region: "EU",
    isoLanguageCode: "no",
    isoCountryCode: "NO",
    stageRootPath: "/no",
    storeRootPath: "/no",
    uiDisplay: "NO",
    textDirection: "ltr",
    isoCurrencyCode: "NOK",
    homePageTitle: "Homepage (Norge)",
    pageTitleSuffix: "Homepage (NO)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "nb-NO",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/no",
      store: "/no",
      goto: "/no/shop/goto",
      support: "https://support.testurl.com/no-no",
      locate: "https://locate.testurl.com/no/no",
      jobs: "/careers/no",
      search: "/no/search",
      education: "/no-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  sv_SE: {
    id: "sv_SE",
    sourceLocale: "src_sv_SE",
    language: "Swedish",
    territory: "Sweden",
    tier: "B",
    region: "EU",
    isoLanguageCode: "sv",
    isoCountryCode: "SE",
    stageRootPath: "/se",
    storeRootPath: "/se",
    uiDisplay: "SE",
    textDirection: "ltr",
    isoCurrencyCode: "SEK",
    homePageTitle: "Homepage (Sverige)",
    pageTitleSuffix: "Homepage (SE)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "sv-SE",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/se",
      store: "/se",
      goto: "/se/shop/goto",
      support: "https://support.testurl.com/sv-se",
      locate: "https://locate.testurl.com/se/sv",
      jobs: "/careers/se",
      search: "/se/search",
      education: "/se-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  es_CO: {
    id: "es_CO",
    sourceLocale: "src_es_CO",
    language: "Spanish",
    territory: "Colombia",
    tier: "A",
    region: "ALAC",
    isoLanguageCode: "es",
    isoCountryCode: "CO",
    stageRootPath: "/co",
    storeRootPath: "",
    uiDisplay: "CO",
    textDirection: "ltr",
    isoCurrencyCode: "COP",
    homePageTitle: "Homepage (Colombia)",
    pageTitleSuffix: "Homepage (CO)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "es-MX",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/co",
      store: "",
      goto: "",
      support: "https://support.testurl.com/es-co",
      locate: "https://locate.testurl.com/co/es",
      jobs: "/careers/co",
      search: "/co/search",
      education: "",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_US: {
    id: "en_US",
    sourceLocale: "",
    language: "English",
    territory: "United States",
    tier: "A",
    region: "WW",
    isoLanguageCode: "en",
    isoCountryCode: "US",
    stageRootPath: "",
    storeRootPath: "/us",
    uiDisplay: "US",
    textDirection: "ltr",
    isoCurrencyCode: "USD",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-US",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "",
      store: "/us",
      goto: "/us/shop/goto",
      support: "https://support.testurl.com",
      locate: "https://locate.testurl.com",
      jobs: "/careers/us",
      search: "/us/search",
      education: "/us-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_IE: {
    id: "en_IE",
    sourceLocale: "src_en_IE",
    language: "English",
    territory: "Ireland",
    tier: "B",
    region: "EU",
    isoLanguageCode: "en",
    isoCountryCode: "IE",
    stageRootPath: "/ie",
    storeRootPath: "/ie",
    uiDisplay: "IE",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Ireland)",
    pageTitleSuffix: "Homepage (IE)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-GB",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/ie",
      store: "/ie",
      goto: "/ie/shop/goto",
      support: "https://support.testurl.com/en-ie",
      locate: "https://locate.testurl.com/ie/en",
      jobs: "/careers/ie",
      search: "/ie/search",
      education: "/ie-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_IN: {
    id: "en_IN",
    sourceLocale: "src_en_IN",
    language: "English",
    territory: "India",
    tier: "A",
    region: "IN",
    isoLanguageCode: "en",
    isoCountryCode: "IN",
    stageRootPath: "/in",
    storeRootPath: "/in",
    uiDisplay: "IN",
    textDirection: "ltr",
    isoCurrencyCode: "INR",
    homePageTitle: "Homepage (India)",
    pageTitleSuffix: "Homepage (IN)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-GB",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/in",
      store: "/in",
      goto: "/in/shop/goto",
      support: "https://support.testurl.com/en-in",
      locate: "https://locate.testurl.com/in/en",
      jobs: "/careers/in",
      search: "/in/search",
      education: "/in-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  de_DE: {
    id: "de_DE",
    sourceLocale: "src_de_DE",
    language: "German",
    territory: "Germany",
    tier: "A",
    region: "EU",
    isoLanguageCode: "de",
    isoCountryCode: "DE",
    stageRootPath: "/de",
    storeRootPath: "/de",
    uiDisplay: "DE",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Deutschland)",
    pageTitleSuffix: "Homepage (DE)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "de-DE",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/de",
      store: "/de",
      goto: "/de/shop/goto",
      support: "https://support.testurl.com/de-de",
      locate: "https://locate.testurl.com/de/de",
      jobs: "/careers/de",
      search: "/de/search",
      education: "/de-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_AU: {
    id: "en_AU",
    sourceLocale: "src_en_AU",
    language: "English",
    territory: "Australia",
    tier: "A",
    region: "ANZ",
    isoLanguageCode: "en",
    isoCountryCode: "AU",
    stageRootPath: "/au",
    storeRootPath: "/au",
    uiDisplay: "AU",
    textDirection: "ltr",
    isoCurrencyCode: "AUD",
    homePageTitle: "Homepage (Australia)",
    pageTitleSuffix: "Homepage (AU)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-AU",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/au",
      store: "/au",
      goto: "/au/shop/goto",
      support: "https://support.testurl.com/en-au",
      locate: "https://locate.testurl.com/au/en",
      jobs: "/careers/au",
      search: "/au/search",
      education: "/au-hed/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  pt_BR: {
    id: "pt_BR",
    sourceLocale: "src_pt_BR",
    language: "Portuguese",
    territory: "Brazil",
    tier: "A",
    region: "ALAC",
    isoLanguageCode: "pt",
    isoCountryCode: "BR",
    stageRootPath: "/br",
    storeRootPath: "/br",
    uiDisplay: "BR",
    textDirection: "ltr",
    isoCurrencyCode: "BRL",
    homePageTitle: "Homepage (Brasil)",
    pageTitleSuffix: "Homepage (BR)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "pt-BR",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/br",
      store: "/br",
      goto: "/br/shop/goto",
      support: "https://support.testurl.com/pt-br",
      locate: "https://locate.testurl.com/br/pt",
      jobs: "/careers/br",
      search: "/br/search",
      education: "/br-hed/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  nl_BE: {
    id: "nl_BE",
    sourceLocale: "src_nl_BE",
    language: "Dutch",
    territory: "Belgium",
    tier: "B",
    region: "EU",
    isoLanguageCode: "nl",
    isoCountryCode: "BE",
    stageRootPath: "/benl",
    storeRootPath: "/be-nl",
    uiDisplay: "BENL",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (BelgiÃ«)",
    pageTitleSuffix: "Homepage (BE)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "nl-NL",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/benl",
      store: "/be-nl",
      goto: "/be-nl/shop/goto",
      support: "https://support.testurl.com/nl-be",
      locate: "https://locate.testurl.com/be/nl",
      jobs: "/careers/benl",
      search: "/be-nl/search",
      education: "/be-nl-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  fr_BE: {
    id: "fr_BE",
    sourceLocale: "src_fr_BE",
    language: "French",
    territory: "Belgium",
    tier: "B",
    region: "EU",
    isoLanguageCode: "fr",
    isoCountryCode: "BE",
    stageRootPath: "/befr",
    storeRootPath: "/be-fr",
    uiDisplay: "BEFR",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Belgique)",
    pageTitleSuffix: "Homepage (BE)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "fr-FR",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/befr",
      store: "/be-fr",
      goto: "/be-fr/shop/goto",
      support: "https://support.testurl.com/fr-be",
      locate: "https://locate.testurl.com/be/fr",
      jobs: "/careers/befr",
      search: "/be-fr/search",
      education: "/be-fr-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  zh_TW: {
    id: "zh_TW",
    sourceLocale: "src_zh_TW",
    language: "Chinese",
    territory: "Taiwan",
    tier: "B",
    region: "GC",
    isoLanguageCode: "zh",
    isoCountryCode: "TW",
    stageRootPath: "/tw",
    storeRootPath: "/tw",
    uiDisplay: "TW",
    textDirection: "ltr",
    isoCurrencyCode: "TWD",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "zh-Hant-TW",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/tw",
      store: "/tw",
      goto: "/tw/shop/goto",
      support: "https://support.testurl.com/zh-tw",
      locate: "https://locate.testurl.com/tw/zh",
      jobs: "/careers/tw",
      search: "/tw/search",
      education: "/tw-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  nl_NL: {
    id: "nl_NL",
    sourceLocale: "src_nl_NL",
    language: "Dutch",
    territory: "Netherlands",
    tier: "B",
    region: "EU",
    isoLanguageCode: "nl",
    isoCountryCode: "NL",
    stageRootPath: "/nl",
    storeRootPath: "/nl",
    uiDisplay: "NL",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Nederland)",
    pageTitleSuffix: "Homepage (NL)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "nl-NL",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/nl",
      store: "/nl",
      goto: "/nl/shop/goto",
      support: "https://support.testurl.com/nl-nl",
      locate: "https://locate.testurl.com/nl/nl",
      jobs: "/careers/nl",
      search: "/nl/search",
      education: "/nl-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  ja_JP: {
    id: "ja_JP",
    sourceLocale: "src_ja_JP",
    language: "Japanese",
    territory: "Japan",
    tier: "A",
    region: "JP",
    isoLanguageCode: "ja",
    isoCountryCode: "JP",
    stageRootPath: "/jp",
    storeRootPath: "/jp",
    uiDisplay: "JP",
    textDirection: "ltr",
    isoCurrencyCode: "JPY",
    homePageTitle: "Homepage",
    pageTitleSuffix: "Homepage",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "ja-JP",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/jp",
      store: "/jp",
      goto: "/jp/shop/goto",
      support: "https://support.testurl.com/ja-jp",
      locate: "https://locate.testurl.com/jp/ja",
      jobs: "/careers/jp",
      search: "/jp/search",
      education: "/jp_edu_1460/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_NZ: {
    id: "en_NZ",
    sourceLocale: "src_en_NZ",
    language: "English",
    territory: "New Zealand",
    tier: "B",
    region: "ANZ",
    isoLanguageCode: "en",
    isoCountryCode: "NZ",
    stageRootPath: "/nz",
    storeRootPath: "/nz",
    uiDisplay: "NZ",
    textDirection: "ltr",
    isoCurrencyCode: "NZD",
    homePageTitle: "Homepage (New Zealand)",
    pageTitleSuffix: "Homepage (NZ)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-AU",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/nz",
      store: "/nz",
      goto: "/nz/shop/goto",
      support: "https://support.testurl.com/en-nz",
      locate: "https://locate.testurl.com/nz/en",
      jobs: "/careers/nz",
      search: "/nz/search",
      developer: "https://developer.apple.com",
      itunes: "https://itunes.apple.com/nz",
      education: "/nz-hed/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  en_HK: {
    id: "en_HK",
    sourceLocale: "src_en_HK",
    language: "English",
    territory: "Hong Kong",
    tier: "B",
    region: "GC",
    isoLanguageCode: "en",
    isoCountryCode: "HK",
    stageRootPath: "/hk/en",
    storeRootPath: "/hk",
    uiDisplay: "HKEN",
    textDirection: "ltr",
    isoCurrencyCode: "HKD",
    homePageTitle: "Homepage (Hong Kong)",
    pageTitleSuffix: "Homepage (HK)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "en-GB",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/hk/en",
      store: "/hk",
      goto: "/hk/shop/goto",
      support: "https://support.testurl.com/en-hk",
      locate: "https://locate.testurl.com/hk/en",
      jobs: "/careers/hk/en",
      search: "/hk/search",
      education: "/hk_edu_13377/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  es_ES: {
    id: "es_ES",
    sourceLocale: "src_es_ES",
    language: "Spanish",
    territory: "Spain",
    tier: "A",
    region: "EU",
    isoLanguageCode: "es",
    isoCountryCode: "ES",
    stageRootPath: "/es",
    storeRootPath: "/es",
    uiDisplay: "ES",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Espana)",
    pageTitleSuffix: "Homepage (ES)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "es-ES",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/es",
      store: "/es",
      goto: "/es/shop/goto",
      support: "https://support.testurl.com/es-es",
      locate: "https://locate.testurl.com/es/es",
      jobs: "/careers/es",
      search: "/es/search",
      education: "/es-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
  pt_PT: {
    id: "pt_PT",
    sourceLocale: "src_pt_PT",
    language: "Portuguese",
    territory: "Portugal",
    tier: "B",
    region: "EU",
    isoLanguageCode: "pt",
    isoCountryCode: "PT",
    stageRootPath: "/pt",
    storeRootPath: "/pt",
    uiDisplay: "PT",
    textDirection: "ltr",
    isoCurrencyCode: "EUR",
    homePageTitle: "Homepage (Portugal)",
    pageTitleSuffix: "Homepage (PT)",
    wwwDomain: "www.testdomain.com",
    media: {
      language: "pt-PT",
      ruts: {
        storefrontId: "12345",
      },
    },
    urlPaths: {
      marcom: "/pt",
      store: "/pt",
      goto: "/pt/shop/goto",
      support: "https://support.testurl.com/pt-pt",
      locate: "https://locate.testurl.com/pt/pt",
      jobs: "/careers/pt",
      search: "/pt/search",
      education: "/pt-edu/shop",
      previewDomain: "testurl.com",
      previewNamespace: "preview",
    },
  },
};
